/*******************************************************************************
* File Name: cycfg_seglcd.h
* Version 1.20
*
* Description: SegLCD display configuration
* This file should not be modified. It was automatically generated by
* Segment LCD Configurator 1.20.0.3158
*
********************************************************************************
* \copyright
* Copyright 2018-2021, Cypress Semiconductor Corporation.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
*******************************************************************************/

#if !defined(H_CYCFG_SEGLCD)
#define H_CYCFG_SEGLCD

#include "syslib/cy_syslib.h"
#include "seglcd/cy_seglcd.h"


/* Set of general parameter of LCD */
#define SegLCD_HW                   LCD0
#define SegLCD_SEG_NUM              32
#define SegLCD_COM_NUM              4
#define SegLCD_CONST_MODIFIER       const

/* Define the common lines for LCD */
#define SegLCD_COM_0                32
#define SegLCD_COM_1                33
#define SegLCD_COM_2                34
#define SegLCD_COM_3                35

/* Define the segment lines for LCD */
#define SegLCD_SEG_0                0
#define SegLCD_SEG_1                1
#define SegLCD_SEG_2                2
#define SegLCD_SEG_3                3
#define SegLCD_SEG_4                4
#define SegLCD_SEG_5                5
#define SegLCD_SEG_6                6
#define SegLCD_SEG_7                7
#define SegLCD_SEG_8                8
#define SegLCD_SEG_9                9
#define SegLCD_SEG_10               10
#define SegLCD_SEG_11               11
#define SegLCD_SEG_12               12
#define SegLCD_SEG_13               13
#define SegLCD_SEG_14               14
#define SegLCD_SEG_15               15
#define SegLCD_SEG_16               16
#define SegLCD_SEG_17               17
#define SegLCD_SEG_18               18
#define SegLCD_SEG_19               19
#define SegLCD_SEG_20               20
#define SegLCD_SEG_21               21
#define SegLCD_SEG_22               22
#define SegLCD_SEG_23               23
#define SegLCD_SEG_24               24
#define SegLCD_SEG_25               25
#define SegLCD_SEG_26               26
#define SegLCD_SEG_27               27
#define SegLCD_SEG_28               28
#define SegLCD_SEG_29               29
#define SegLCD_SEG_30               30
#define SegLCD_SEG_31               31

/* Define the common row for LCD */
#define LCD_Seg_COM0_ROW            CY_SEGLCD_COMMON(SegLCD_COM_0, 0UL)
#define LCD_Seg_COM1_ROW            CY_SEGLCD_COMMON(SegLCD_COM_1, 1UL)
#define LCD_Seg_COM2_ROW            CY_SEGLCD_COMMON(SegLCD_COM_2, 2UL)
#define LCD_Seg_COM3_ROW            CY_SEGLCD_COMMON(SegLCD_COM_3, 3UL)

/* Define the pixels for LCD
 *         CA'  ----A----		
 *		| \ | / |               Convention for pixel mapping
 *		F H I J B		pixel id : HxxSy_z 		
 *		|  \|/  |
 *              -G-- --K-		xx 	- number of segments in the display 
 *		|  /|\  |		y 	- symbol number in the display 1 to 8
 *		E N M L C 		z 	- pixel id for symbol as shown A to N, CA, DP
 *		| / | \ |
 *		----D---- *DP
 *
 * Segment 0 definition */
#define LCD_Seg_H16S1_D             CY_SEGLCD_PIXEL(SegLCD_SEG_0,  SegLCD_COM_0)
#define LCD_Seg_H16S1_E             CY_SEGLCD_PIXEL(SegLCD_SEG_0,  SegLCD_COM_1)
#define LCD_Seg_H16S1_F             CY_SEGLCD_PIXEL(SegLCD_SEG_0,  SegLCD_COM_2)
#define LCD_Seg_H16S1_CA            CY_SEGLCD_PIXEL(SegLCD_SEG_0,  SegLCD_COM_3)
/* Segment 1 definition */
#define LCD_Seg_H16S1_L             CY_SEGLCD_PIXEL(SegLCD_SEG_1,  SegLCD_COM_0)
#define LCD_Seg_H16S1_K             CY_SEGLCD_PIXEL(SegLCD_SEG_1,  SegLCD_COM_1)
#define LCD_Seg_H16S1_J             CY_SEGLCD_PIXEL(SegLCD_SEG_1,  SegLCD_COM_2)
#define LCD_Seg_H16S1_I             CY_SEGLCD_PIXEL(SegLCD_SEG_1,  SegLCD_COM_3)
/* Segment 2 definition */
#define LCD_Seg_H16S2_D             CY_SEGLCD_PIXEL(SegLCD_SEG_2,  SegLCD_COM_0)
#define LCD_Seg_H16S2_E             CY_SEGLCD_PIXEL(SegLCD_SEG_2,  SegLCD_COM_1)
#define LCD_Seg_H16S2_F             CY_SEGLCD_PIXEL(SegLCD_SEG_2,  SegLCD_COM_2)
#define LCD_Seg_H16S2_CA            CY_SEGLCD_PIXEL(SegLCD_SEG_2,  SegLCD_COM_3)
/* Segment 3 definition */
#define LCD_Seg_H16S2_L             CY_SEGLCD_PIXEL(SegLCD_SEG_3,  SegLCD_COM_0)
#define LCD_Seg_H16S2_K             CY_SEGLCD_PIXEL(SegLCD_SEG_3,  SegLCD_COM_1)
#define LCD_Seg_H16S2_J             CY_SEGLCD_PIXEL(SegLCD_SEG_3,  SegLCD_COM_2)
#define LCD_Seg_H16S2_I             CY_SEGLCD_PIXEL(SegLCD_SEG_3,  SegLCD_COM_3)
/* Segment 4 definition */
#define LCD_Seg_H16S3_D             CY_SEGLCD_PIXEL(SegLCD_SEG_4,  SegLCD_COM_0)
#define LCD_Seg_H16S3_E             CY_SEGLCD_PIXEL(SegLCD_SEG_4,  SegLCD_COM_1)
#define LCD_Seg_H16S3_F             CY_SEGLCD_PIXEL(SegLCD_SEG_4,  SegLCD_COM_2)
#define LCD_Seg_H16S3_CA            CY_SEGLCD_PIXEL(SegLCD_SEG_4,  SegLCD_COM_3)
/* Segment 5 definition */
#define LCD_Seg_H16S3_L             CY_SEGLCD_PIXEL(SegLCD_SEG_5,  SegLCD_COM_0)
#define LCD_Seg_H16S3_K             CY_SEGLCD_PIXEL(SegLCD_SEG_5,  SegLCD_COM_1)
#define LCD_Seg_H16S3_J             CY_SEGLCD_PIXEL(SegLCD_SEG_5,  SegLCD_COM_2)
#define LCD_Seg_H16S3_I             CY_SEGLCD_PIXEL(SegLCD_SEG_5,  SegLCD_COM_3)
/* Segment 6 definition */
#define LCD_Seg_H16S4_D             CY_SEGLCD_PIXEL(SegLCD_SEG_6,  SegLCD_COM_0)
#define LCD_Seg_H16S4_E             CY_SEGLCD_PIXEL(SegLCD_SEG_6,  SegLCD_COM_1)
#define LCD_Seg_H16S4_F             CY_SEGLCD_PIXEL(SegLCD_SEG_6,  SegLCD_COM_2)
#define LCD_Seg_H16S4_CA            CY_SEGLCD_PIXEL(SegLCD_SEG_6,  SegLCD_COM_3)
/* Segment 7 definition */
#define LCD_Seg_H16S4_L             CY_SEGLCD_PIXEL(SegLCD_SEG_7,  SegLCD_COM_0)
#define LCD_Seg_H16S4_K             CY_SEGLCD_PIXEL(SegLCD_SEG_7,  SegLCD_COM_1)
#define LCD_Seg_H16S4_J             CY_SEGLCD_PIXEL(SegLCD_SEG_7,  SegLCD_COM_2)
#define LCD_Seg_H16S4_I             CY_SEGLCD_PIXEL(SegLCD_SEG_7,  SegLCD_COM_3)
/* Segment 8 definition */
#define LCD_Seg_H16S5_D             CY_SEGLCD_PIXEL(SegLCD_SEG_8,  SegLCD_COM_0)
#define LCD_Seg_H16S5_E             CY_SEGLCD_PIXEL(SegLCD_SEG_8,  SegLCD_COM_1)
#define LCD_Seg_H16S5_F             CY_SEGLCD_PIXEL(SegLCD_SEG_8,  SegLCD_COM_2)
#define LCD_Seg_H16S5_CA            CY_SEGLCD_PIXEL(SegLCD_SEG_8,  SegLCD_COM_3)
/* Segment 9 definition */
#define LCD_Seg_H16S5_L             CY_SEGLCD_PIXEL(SegLCD_SEG_9,  SegLCD_COM_0)
#define LCD_Seg_H16S5_K             CY_SEGLCD_PIXEL(SegLCD_SEG_9,  SegLCD_COM_1)
#define LCD_Seg_H16S5_J             CY_SEGLCD_PIXEL(SegLCD_SEG_9,  SegLCD_COM_2)
#define LCD_Seg_H16S5_I             CY_SEGLCD_PIXEL(SegLCD_SEG_9,  SegLCD_COM_3)
/* Segment 10 definition */
#define LCD_Seg_H16S6_D             CY_SEGLCD_PIXEL(SegLCD_SEG_10, SegLCD_COM_0)
#define LCD_Seg_H16S6_E             CY_SEGLCD_PIXEL(SegLCD_SEG_10, SegLCD_COM_1)
#define LCD_Seg_H16S6_F             CY_SEGLCD_PIXEL(SegLCD_SEG_10, SegLCD_COM_2)
#define LCD_Seg_H16S6_CA            CY_SEGLCD_PIXEL(SegLCD_SEG_10, SegLCD_COM_3)
/* Segment 11 definition */
#define LCD_Seg_H16S6_L             CY_SEGLCD_PIXEL(SegLCD_SEG_11, SegLCD_COM_0)
#define LCD_Seg_H16S6_K             CY_SEGLCD_PIXEL(SegLCD_SEG_11, SegLCD_COM_1)
#define LCD_Seg_H16S6_J             CY_SEGLCD_PIXEL(SegLCD_SEG_11, SegLCD_COM_2)
#define LCD_Seg_H16S6_I             CY_SEGLCD_PIXEL(SegLCD_SEG_11, SegLCD_COM_3)
/* Segment 12 definition */
#define LCD_Seg_H16S7_D             CY_SEGLCD_PIXEL(SegLCD_SEG_12, SegLCD_COM_0)
#define LCD_Seg_H16S7_E             CY_SEGLCD_PIXEL(SegLCD_SEG_12, SegLCD_COM_1)
#define LCD_Seg_H16S7_F             CY_SEGLCD_PIXEL(SegLCD_SEG_12, SegLCD_COM_2)
#define LCD_Seg_H16S7_CA            CY_SEGLCD_PIXEL(SegLCD_SEG_12, SegLCD_COM_3)
/* Segment 13 definition */
#define LCD_Seg_H16S7_L             CY_SEGLCD_PIXEL(SegLCD_SEG_13, SegLCD_COM_0)
#define LCD_Seg_H16S7_K             CY_SEGLCD_PIXEL(SegLCD_SEG_13, SegLCD_COM_1)
#define LCD_Seg_H16S7_J             CY_SEGLCD_PIXEL(SegLCD_SEG_13, SegLCD_COM_2)
#define LCD_Seg_H16S7_I             CY_SEGLCD_PIXEL(SegLCD_SEG_13, SegLCD_COM_3)
/* Segment 14 definition */
#define LCD_Seg_H16S8_D             CY_SEGLCD_PIXEL(SegLCD_SEG_14, SegLCD_COM_0)
#define LCD_Seg_H16S8_E             CY_SEGLCD_PIXEL(SegLCD_SEG_14, SegLCD_COM_1)
#define LCD_Seg_H16S8_F             CY_SEGLCD_PIXEL(SegLCD_SEG_14, SegLCD_COM_2)
#define LCD_Seg_H16S8_CA            CY_SEGLCD_PIXEL(SegLCD_SEG_14, SegLCD_COM_3)
/* Segment 15 definition */
#define LCD_Seg_H16S8_L             CY_SEGLCD_PIXEL(SegLCD_SEG_15, SegLCD_COM_0)
#define LCD_Seg_H16S8_K             CY_SEGLCD_PIXEL(SegLCD_SEG_15, SegLCD_COM_1)
#define LCD_Seg_H16S8_J             CY_SEGLCD_PIXEL(SegLCD_SEG_15, SegLCD_COM_2)
#define LCD_Seg_H16S8_I             CY_SEGLCD_PIXEL(SegLCD_SEG_15, SegLCD_COM_3)
/* Segment 16 definition */
#define LCD_Seg_H16S8_DP            CY_SEGLCD_PIXEL(SegLCD_SEG_16, SegLCD_COM_0)
#define LCD_Seg_H16S8_C             CY_SEGLCD_PIXEL(SegLCD_SEG_16, SegLCD_COM_1)
#define LCD_Seg_H16S8_B             CY_SEGLCD_PIXEL(SegLCD_SEG_16, SegLCD_COM_2)
#define LCD_Seg_H16S8_A             CY_SEGLCD_PIXEL(SegLCD_SEG_16, SegLCD_COM_3)
/* Segment 17 definition */
#define LCD_Seg_H16S8_M             CY_SEGLCD_PIXEL(SegLCD_SEG_17, SegLCD_COM_0)
#define LCD_Seg_H16S8_N             CY_SEGLCD_PIXEL(SegLCD_SEG_17, SegLCD_COM_1)
#define LCD_Seg_H16S8_G             CY_SEGLCD_PIXEL(SegLCD_SEG_17, SegLCD_COM_2)
#define LCD_Seg_H16S8_H             CY_SEGLCD_PIXEL(SegLCD_SEG_17, SegLCD_COM_3)
/* Segment 18 definition */
#define LCD_Seg_H16S7_DP            CY_SEGLCD_PIXEL(SegLCD_SEG_18, SegLCD_COM_0)
#define LCD_Seg_H16S7_C             CY_SEGLCD_PIXEL(SegLCD_SEG_18, SegLCD_COM_1)
#define LCD_Seg_H16S7_B             CY_SEGLCD_PIXEL(SegLCD_SEG_18, SegLCD_COM_2)
#define LCD_Seg_H16S7_A             CY_SEGLCD_PIXEL(SegLCD_SEG_18, SegLCD_COM_3)
/* Segment 19 definition */
#define LCD_Seg_H16S7_M             CY_SEGLCD_PIXEL(SegLCD_SEG_19, SegLCD_COM_0)
#define LCD_Seg_H16S7_N             CY_SEGLCD_PIXEL(SegLCD_SEG_19, SegLCD_COM_1)
#define LCD_Seg_H16S7_G             CY_SEGLCD_PIXEL(SegLCD_SEG_19, SegLCD_COM_2)
#define LCD_Seg_H16S7_H             CY_SEGLCD_PIXEL(SegLCD_SEG_19, SegLCD_COM_3)
/* Segment 20 definition */
#define LCD_Seg_H16S6_DP            CY_SEGLCD_PIXEL(SegLCD_SEG_20, SegLCD_COM_0)
#define LCD_Seg_H16S6_C             CY_SEGLCD_PIXEL(SegLCD_SEG_20, SegLCD_COM_1)
#define LCD_Seg_H16S6_B             CY_SEGLCD_PIXEL(SegLCD_SEG_20, SegLCD_COM_2)
#define LCD_Seg_H16S6_A             CY_SEGLCD_PIXEL(SegLCD_SEG_20, SegLCD_COM_3)
/* Segment 21 definition */
#define LCD_Seg_H16S6_M             CY_SEGLCD_PIXEL(SegLCD_SEG_21, SegLCD_COM_0)
#define LCD_Seg_H16S6_N             CY_SEGLCD_PIXEL(SegLCD_SEG_21, SegLCD_COM_1)
#define LCD_Seg_H16S6_G             CY_SEGLCD_PIXEL(SegLCD_SEG_21, SegLCD_COM_2)
#define LCD_Seg_H16S6_H             CY_SEGLCD_PIXEL(SegLCD_SEG_21, SegLCD_COM_3)
/* Segment 22 definition */
#define LCD_Seg_H16S5_DP            CY_SEGLCD_PIXEL(SegLCD_SEG_22, SegLCD_COM_0)
#define LCD_Seg_H16S5_C             CY_SEGLCD_PIXEL(SegLCD_SEG_22, SegLCD_COM_1)
#define LCD_Seg_H16S5_B             CY_SEGLCD_PIXEL(SegLCD_SEG_22, SegLCD_COM_2)
#define LCD_Seg_H16S5_A             CY_SEGLCD_PIXEL(SegLCD_SEG_22, SegLCD_COM_3)
/* Segment 23 definition */
#define LCD_Seg_H16S5_M             CY_SEGLCD_PIXEL(SegLCD_SEG_23, SegLCD_COM_0)
#define LCD_Seg_H16S5_N             CY_SEGLCD_PIXEL(SegLCD_SEG_23, SegLCD_COM_1)
#define LCD_Seg_H16S5_G             CY_SEGLCD_PIXEL(SegLCD_SEG_23, SegLCD_COM_2)
#define LCD_Seg_H16S5_H             CY_SEGLCD_PIXEL(SegLCD_SEG_23, SegLCD_COM_3)
/* Segment 24 definition */
#define LCD_Seg_H16S4_DP            CY_SEGLCD_PIXEL(SegLCD_SEG_24, SegLCD_COM_0)
#define LCD_Seg_H16S4_C             CY_SEGLCD_PIXEL(SegLCD_SEG_24, SegLCD_COM_1)
#define LCD_Seg_H16S4_B             CY_SEGLCD_PIXEL(SegLCD_SEG_24, SegLCD_COM_2)
#define LCD_Seg_H16S4_A             CY_SEGLCD_PIXEL(SegLCD_SEG_24, SegLCD_COM_3)
/* Segment 25 definition */
#define LCD_Seg_H16S4_M             CY_SEGLCD_PIXEL(SegLCD_SEG_25, SegLCD_COM_0)
#define LCD_Seg_H16S4_N             CY_SEGLCD_PIXEL(SegLCD_SEG_25, SegLCD_COM_1)
#define LCD_Seg_H16S4_G             CY_SEGLCD_PIXEL(SegLCD_SEG_25, SegLCD_COM_2)
#define LCD_Seg_H16S4_H             CY_SEGLCD_PIXEL(SegLCD_SEG_25, SegLCD_COM_3)
/* Segment 26 definition */
#define LCD_Seg_H16S3_DP            CY_SEGLCD_PIXEL(SegLCD_SEG_26, SegLCD_COM_0)
#define LCD_Seg_H16S3_C             CY_SEGLCD_PIXEL(SegLCD_SEG_26, SegLCD_COM_1)
#define LCD_Seg_H16S3_B             CY_SEGLCD_PIXEL(SegLCD_SEG_26, SegLCD_COM_2)
#define LCD_Seg_H16S3_A             CY_SEGLCD_PIXEL(SegLCD_SEG_26, SegLCD_COM_3)
/* Segment 27 definition */
#define LCD_Seg_H16S3_M             CY_SEGLCD_PIXEL(SegLCD_SEG_27, SegLCD_COM_0)
#define LCD_Seg_H16S3_N             CY_SEGLCD_PIXEL(SegLCD_SEG_27, SegLCD_COM_1)
#define LCD_Seg_H16S3_G             CY_SEGLCD_PIXEL(SegLCD_SEG_27, SegLCD_COM_2)
#define LCD_Seg_H16S3_H             CY_SEGLCD_PIXEL(SegLCD_SEG_27, SegLCD_COM_3)
/* Segment 28 definition */
#define LCD_Seg_H16S2_DP            CY_SEGLCD_PIXEL(SegLCD_SEG_28, SegLCD_COM_0)
#define LCD_Seg_H16S2_C             CY_SEGLCD_PIXEL(SegLCD_SEG_28, SegLCD_COM_1)
#define LCD_Seg_H16S2_B             CY_SEGLCD_PIXEL(SegLCD_SEG_28, SegLCD_COM_2)
#define LCD_Seg_H16S2_A             CY_SEGLCD_PIXEL(SegLCD_SEG_28, SegLCD_COM_3)
/* Segment 29 definition */
#define LCD_Seg_H16S2_M             CY_SEGLCD_PIXEL(SegLCD_SEG_29, SegLCD_COM_0)
#define LCD_Seg_H16S2_N             CY_SEGLCD_PIXEL(SegLCD_SEG_29, SegLCD_COM_1)
#define LCD_Seg_H16S2_G             CY_SEGLCD_PIXEL(SegLCD_SEG_29, SegLCD_COM_2)
#define LCD_Seg_H16S2_H             CY_SEGLCD_PIXEL(SegLCD_SEG_29, SegLCD_COM_3)
/* Segment 30 definition */
#define LCD_Seg_H16S1_DP            CY_SEGLCD_PIXEL(SegLCD_SEG_30, SegLCD_COM_0)
#define LCD_Seg_H16S1_C             CY_SEGLCD_PIXEL(SegLCD_SEG_30, SegLCD_COM_1)
#define LCD_Seg_H16S1_B             CY_SEGLCD_PIXEL(SegLCD_SEG_30, SegLCD_COM_2)
#define LCD_Seg_H16S1_A             CY_SEGLCD_PIXEL(SegLCD_SEG_30, SegLCD_COM_3)
/* Segment 31 definition */
#define LCD_Seg_H16S1_M             CY_SEGLCD_PIXEL(SegLCD_SEG_31, SegLCD_COM_0)
#define LCD_Seg_H16S1_N             CY_SEGLCD_PIXEL(SegLCD_SEG_31, SegLCD_COM_1)
#define LCD_Seg_H16S1_G             CY_SEGLCD_PIXEL(SegLCD_SEG_31, SegLCD_COM_2)
#define LCD_Seg_H16S1_H             CY_SEGLCD_PIXEL(SegLCD_SEG_31, SegLCD_COM_3)


/* Define the display pixel bits mask */
#define LCD_Seg_PIXEL_A             0x0001
#define LCD_Seg_PIXEL_B             0x0002
#define LCD_Seg_PIXEL_C             0x0004
#define LCD_Seg_PIXEL_D             0x0008
#define LCD_Seg_PIXEL_E             0x0010
#define LCD_Seg_PIXEL_F             0x0020
#define LCD_Seg_PIXEL_G             0x0040
#define LCD_Seg_PIXEL_H             0x0080
#define LCD_Seg_PIXEL_I             0x0100
#define LCD_Seg_PIXEL_J             0x0200
#define LCD_Seg_PIXEL_K             0x0400
#define LCD_Seg_PIXEL_L             0x0800
#define LCD_Seg_PIXEL_M             0x1000
#define LCD_Seg_PIXEL_N             0x2000
#define LCD_Seg_PIXEL_CA            0x4000
#define LCD_Seg_PIXEL_DP            0x8000


/* Define the display properties like no of segment and symbol */
#define SegLCD_Display0_TYPE        ((uint32_t)CY_SEGLCD_16SEG)
#define SegLCD_Display0_SYM_NUM     (8UL)


/* Set of common lines definition */
SegLCD_CONST_MODIFIER uint32_t SegLCD_commons[SegLCD_COM_NUM] =
{
    LCD_Seg_COM0_ROW,       /* Display common row 0 */
    LCD_Seg_COM1_ROW,       /* Display common row 1 */
    LCD_Seg_COM2_ROW,       /* Display common row 2 */
    LCD_Seg_COM3_ROW,       /* Display common row 3 */
};


/* Displays pixel array and structure definitions */
SegLCD_CONST_MODIFIER uint32_t SegLCD_Display0_pixMap[SegLCD_Display0_SYM_NUM][SegLCD_Display0_TYPE] =
{
    {
        LCD_Seg_H16S1_A,    /* Display0_0_A */
        LCD_Seg_H16S1_B,    /* Display0_0_B */
        LCD_Seg_H16S1_C,    /* Display0_0_C */
        LCD_Seg_H16S1_D,    /* Display0_0_D */
        LCD_Seg_H16S1_E,    /* Display0_0_E */
        LCD_Seg_H16S1_F,    /* Display0_0_F */
        LCD_Seg_H16S1_G,    /* Display0_0_G */
        LCD_Seg_H16S1_H,    /* Display0_0_H */
        LCD_Seg_H16S1_I,    /* Display0_0_I */
        LCD_Seg_H16S1_J,    /* Display0_0_J */
        LCD_Seg_H16S1_K,    /* Display0_0_K */
        LCD_Seg_H16S1_L,    /* Display0_0_L */
        LCD_Seg_H16S1_M,    /* Display0_0_M */
        LCD_Seg_H16S1_N,    /* Display0_0_N */
        LCD_Seg_H16S1_CA,   /* Display0_0_CA */
        LCD_Seg_H16S1_DP,   /* Display0_0_DP */
    },
    {
        LCD_Seg_H16S2_A,    /* Display0_1_A */
        LCD_Seg_H16S2_B,    /* Display0_1_B */
        LCD_Seg_H16S2_C,    /* Display0_1_C */
        LCD_Seg_H16S2_D,    /* Display0_1_D */
        LCD_Seg_H16S2_E,    /* Display0_1_E */
        LCD_Seg_H16S2_F,    /* Display0_1_F */
        LCD_Seg_H16S2_G,    /* Display0_1_G */
        LCD_Seg_H16S2_H,    /* Display0_1_H */
        LCD_Seg_H16S2_I,    /* Display0_1_I */
        LCD_Seg_H16S2_J,    /* Display0_1_J */
        LCD_Seg_H16S2_K,    /* Display0_1_K */
        LCD_Seg_H16S2_L,    /* Display0_1_L */
        LCD_Seg_H16S2_M,    /* Display0_1_M */
        LCD_Seg_H16S2_N,    /* Display0_1_N */
        LCD_Seg_H16S2_CA,   /* Display0_1_CA */
        LCD_Seg_H16S2_DP,   /* Display0_1_DP */
    },
    {
        LCD_Seg_H16S3_A,    /* Display0_2_A */
        LCD_Seg_H16S3_B,    /* Display0_2_B */
        LCD_Seg_H16S3_C,    /* Display0_2_C */
        LCD_Seg_H16S3_D,    /* Display0_2_D */
        LCD_Seg_H16S3_E,    /* Display0_2_E */
        LCD_Seg_H16S3_F,    /* Display0_2_F */
        LCD_Seg_H16S3_G,    /* Display0_2_G */
        LCD_Seg_H16S3_H,    /* Display0_2_H */
        LCD_Seg_H16S3_I,    /* Display0_2_I */
        LCD_Seg_H16S3_J,    /* Display0_2_J */
        LCD_Seg_H16S3_K,    /* Display0_2_K */
        LCD_Seg_H16S3_L,    /* Display0_2_L */
        LCD_Seg_H16S3_M,    /* Display0_2_M */
        LCD_Seg_H16S3_N,    /* Display0_2_N */
        LCD_Seg_H16S3_CA,   /* Display0_2_CA */
        LCD_Seg_H16S3_DP,   /* Display0_2_DP */
    },
    {
        LCD_Seg_H16S4_A,    /* Display0_3_A */
        LCD_Seg_H16S4_B,    /* Display0_3_B */
        LCD_Seg_H16S4_C,    /* Display0_3_C */
        LCD_Seg_H16S4_D,    /* Display0_3_D */
        LCD_Seg_H16S4_E,    /* Display0_3_E */
        LCD_Seg_H16S4_F,    /* Display0_3_F */
        LCD_Seg_H16S4_G,    /* Display0_3_G */
        LCD_Seg_H16S4_H,    /* Display0_3_H */
        LCD_Seg_H16S4_I,    /* Display0_3_I */
        LCD_Seg_H16S4_J,    /* Display0_3_J */
        LCD_Seg_H16S4_K,    /* Display0_3_K */
        LCD_Seg_H16S4_L,    /* Display0_3_L */
        LCD_Seg_H16S4_M,    /* Display0_3_M */
        LCD_Seg_H16S4_N,    /* Display0_3_N */
        LCD_Seg_H16S4_CA,   /* Display0_3_CA */
        LCD_Seg_H16S4_DP,   /* Display0_3_DP */
    },
    {
        LCD_Seg_H16S5_A,    /* Display0_4_A */
        LCD_Seg_H16S5_B,    /* Display0_4_B */
        LCD_Seg_H16S5_C,    /* Display0_4_C */
        LCD_Seg_H16S5_D,    /* Display0_4_D */
        LCD_Seg_H16S5_E,    /* Display0_4_E */
        LCD_Seg_H16S5_F,    /* Display0_4_F */
        LCD_Seg_H16S5_G,    /* Display0_4_G */
        LCD_Seg_H16S5_H,    /* Display0_4_H */
        LCD_Seg_H16S5_I,    /* Display0_4_I */
        LCD_Seg_H16S5_J,    /* Display0_4_J */
        LCD_Seg_H16S5_K,    /* Display0_4_K */
        LCD_Seg_H16S5_L,    /* Display0_4_L */
        LCD_Seg_H16S5_M,    /* Display0_4_M */
        LCD_Seg_H16S5_N,    /* Display0_4_N */
        LCD_Seg_H16S5_CA,   /* Display0_4_CA */
        LCD_Seg_H16S5_DP,   /* Display0_4_DP */
    },
    {
        LCD_Seg_H16S6_A,    /* Display0_5_A */
        LCD_Seg_H16S6_B,    /* Display0_5_B */
        LCD_Seg_H16S6_C,    /* Display0_5_C */
        LCD_Seg_H16S6_D,    /* Display0_5_D */
        LCD_Seg_H16S6_E,    /* Display0_5_E */
        LCD_Seg_H16S6_F,    /* Display0_5_F */
        LCD_Seg_H16S6_G,    /* Display0_5_G */
        LCD_Seg_H16S6_H,    /* Display0_5_H */
        LCD_Seg_H16S6_I,    /* Display0_5_I */
        LCD_Seg_H16S6_J,    /* Display0_5_J */
        LCD_Seg_H16S6_K,    /* Display0_5_K */
        LCD_Seg_H16S6_L,    /* Display0_5_L */
        LCD_Seg_H16S6_M,    /* Display0_5_M */
        LCD_Seg_H16S6_N,    /* Display0_5_N */
        LCD_Seg_H16S6_CA,   /* Display0_5_CA */
        LCD_Seg_H16S6_DP,   /* Display0_5_DP */
    },
    {
        LCD_Seg_H16S7_A,    /* Display0_6_A */
        LCD_Seg_H16S7_B,    /* Display0_6_B */
        LCD_Seg_H16S7_C,    /* Display0_6_C */
        LCD_Seg_H16S7_D,    /* Display0_6_D */
        LCD_Seg_H16S7_E,    /* Display0_6_E */
        LCD_Seg_H16S7_F,    /* Display0_6_F */
        LCD_Seg_H16S7_G,    /* Display0_6_G */
        LCD_Seg_H16S7_H,    /* Display0_6_H */
        LCD_Seg_H16S7_I,    /* Display0_6_I */
        LCD_Seg_H16S7_J,    /* Display0_6_J */
        LCD_Seg_H16S7_K,    /* Display0_6_K */
        LCD_Seg_H16S7_L,    /* Display0_6_L */
        LCD_Seg_H16S7_M,    /* Display0_6_M */
        LCD_Seg_H16S7_N,    /* Display0_6_N */
        LCD_Seg_H16S7_CA,   /* Display0_6_CA */
        LCD_Seg_H16S7_DP,   /* Display0_6_DP */
    },
    {
        LCD_Seg_H16S8_A,    /* Display0_7_A */
        LCD_Seg_H16S8_B,    /* Display0_7_B */
        LCD_Seg_H16S8_C,    /* Display0_7_C */
        LCD_Seg_H16S8_D,    /* Display0_7_D */
        LCD_Seg_H16S8_E,    /* Display0_7_E */
        LCD_Seg_H16S8_F,    /* Display0_7_F */
        LCD_Seg_H16S8_G,    /* Display0_7_G */
        LCD_Seg_H16S8_H,    /* Display0_7_H */
        LCD_Seg_H16S8_I,    /* Display0_7_I */
        LCD_Seg_H16S8_J,    /* Display0_7_J */
        LCD_Seg_H16S8_K,    /* Display0_7_K */
        LCD_Seg_H16S8_L,    /* Display0_7_L */
        LCD_Seg_H16S8_M,    /* Display0_7_M */
        LCD_Seg_H16S8_N,    /* Display0_7_N */
        LCD_Seg_H16S8_CA,   /* Display0_7_CA */
        LCD_Seg_H16S8_DP,   /* Display0_7_DP */
    },
};


/* This font map is valid for 16 segment VIM-878 or compatible display
 * SegLCD_Dis/lay0_pixMap      DP CA N  M      L K J I      H G F E      D C B A 
 * {0x003F},   // '0' --       0  0  0  0      0 0 0 0      0 0 1 1      1 1 1 1 
 * {0x0006},   // '1' --       0  0  0  0      0 0 0 0      0 0 0 0      0 1 1 0 
 * {0x045B},   // '2' --       0  0  0  0      0 1 0 0      0 1 0 1      1 0 1 1 
 * {0x044F},   // '3' --       0  0  0  0      0 1 0 0      0 1 0 0      1 1 1 1 
 * {0x0466},   // '4' --       0  0  0  0      0 1 0 0      0 1 1 0      0 1 1 0 
 * {0x046D},   // '5' --       0  0  0  0      0 1 0 0      0 1 1 0      1 1 0 1 
 * {0x047D},   // '6' --       0  0  0  0      0 1 0 0      0 1 1 1      1 1 0 1 
 * {0x0007},   // '7' --       0  0  0  0      0 0 0 0      0 0 0 0      0 1 1 1 
 * {0x047F},   // '8' --       0  0  0  0      0 1 0 0      0 1 1 1      1 1 1 1 
 * {0x046F},   // '9' --       0  0  0  0      0 1 0 0      0 1 1 0      1 1 1 1 
 * {0x0477},   // 'A' --       0  0  0  0      0 1 0 0      0 1 1 1      0 1 1 1 
 * {0x150F},   // 'B' --       0  0  0  1      0 1 0 1      0 0 0 0      1 1 1 1 
 * {0x0039},   // 'C' --       0  0  0  0      0 0 0 0      0 0 1 1      1 0 0 1 
 * {0x110F},   // 'D' --       0  0  0  1      0 0 0 1      0 0 0 0      1 1 1 1 
 * {0x0079},   // 'E' --       0  0  0  0      0 0 0 0      0 1 1 1      1 0 0 1 
 * {0x0071},   // 'F' --       0  0  0  0      0 0 0 0      0 1 1 1      0 0 0 1 
 * {0x043D},   // 'G' --       0  0  0  0      0 1 0 0      0 0 1 1      1 1 0 1 
 * {0x0476},   // 'H' --       0  0  0  0      0 1 0 0      0 1 1 1      0 1 1 0 
 * {0x1109},   // 'I' --       0  0  0  1      0 0 0 1      0 0 0 0      1 0 0 1 
 * {0x001F},   // 'J' --       0  0  0  0      0 0 0 0      0 0 0 1      1 1 1 1 
 * {0x0A70},   // 'K' --       0  0  0  0      1 0 1 0      0 1 1 1      0 0 0 0 
 * {0x0038},   // 'L' --       0  0  0  0      0 0 0 0      0 0 1 1      1 0 0 0 
 * {0x02B6},   // 'M' --       0  0  0  0      0 0 1 0      1 0 1 1      0 1 1 0 
 * {0x08B6},   // 'N' --       0  0  0  0      1 0 0 0      1 0 1 1      0 1 1 0 
 * {0x003F},   // 'O' --       0  0  0  0      0 0 0 0      0 0 1 1      1 1 1 1 
 * {0x0473},   // 'P' --       0  0  0  0      0 1 0 0      0 1 1 1      0 0 1 1 
 * {0x083F},   // 'Q' --       0  0  0  0      1 0 0 0      0 0 1 1      1 1 1 1 
 * {0x0C73},   // 'R' --       0  0  0  0      1 1 0 0      0 1 1 1      0 0 1 1 
 * {0x046D},   // 'S' --       0  0  0  0      0 1 0 0      0 1 1 0      1 1 0 1 
 * {0x1101},   // 'T' --       0  0  0  1      0 0 0 1      0 0 0 0      0 0 0 1 
 * {0x003E},   // 'U' --       0  0  0  0      0 0 0 0      0 0 1 1      1 1 1 0 
 * {0x2230},   // 'V' --       0  0  1  0      0 0 1 0      0 0 1 1      0 0 0 0 
 * {0x2836},   // 'W' --       0  0  1  0      1 0 0 0      0 0 1 1      0 1 1 0 
 * {0x2A80},   // 'X' --       0  0  1  0      1 0 1 0      1 0 0 0      0 0 0 0 
 * {0x1280},   // 'Y' --       0  0  0  1      0 0 1 0      1 0 0 0      0 0 0 0 
 * {0x2209},   // 'Z' --       0  0  1  0      0 0 1 0      0 0 0 0      1 0 0 1 
 * {0x0000},   // '_' --       0  0  0  0      0 0 0 0      0 0 0 0      0 0 0 0 
 * {0x8006},   // '!' --       1  0  0  0      0 0 0 0      0 0 0 0      0 1 1 0 
 * {0x0120},   // '"' --       0  0  0  0      0 0 0 1      0 0 1 0      0 0 0 0 
 * {0x0000},   // '#' --       NA                                                
 * {0x156D},   // '$' --       0  0  0  1      0 1 0 1      0 1 1 0      1 1 0 1 
 * {0x2640},   // '%' --       0  0  1  0      0 1 1 0      0 1 0 0      0 0 0 0 
 * {0x0000},   // '&' --       NA                                                
 * {0x4000},   // ''' --       0  1  0  0      0 0 0 0      0 0 0 0      0 0 0 0 
 * {0x0A00},   // '(' --       0  0  0  0      1 0 1 0      0 0 0 0      0 0 0 0 
 * {0x2080},   // ')' --       0  0  1  0      0 0 0 0      1 0 0 0      0 0 0 0 
 * {0x3B80},   // '*' --       0  0  1  1      1 0 1 1      1 0 0 0      0 0 0 0 
 * {0x1540},   // '+' --       0  0  0  1      0 1 0 1      0 1 0 0      0 0 0 0 
 * {0x0000},   // ',' --       NA                                                
 * {0x0440},   // '-' --       0  0  0  0      0 1 0 0      0 1 0 0      0 0 0 0 
 * {0x8000},   // '.' --       1  0  0  0      0 0 0 0      0 0 0 0      0 0 0 0 
 * {0x2200},   // '/' --       0  0  1  0      0 0 1 0      0 0 0 0      0 0 0 0 
 * {0x9403},   // '?' --       1  0  0  1      0 1 0 0      0 0 0 0      0 0 1 1 
 * {0x0880},   // '\' --       0  0  0  0      1 0 0 0      1 0 0 0      0 0 0 0 
 * {0x0008},   // '_' --       0  0  0  0      0 0 0 0      0 0 0 0      1 0 0 0 
 * {0x1100},   // '|' --       0  0  0  1      0 0 0 1      0 0 0 0      0 0 0 0
 * only these fonts are available for the usage
 */

/* Actual font map for TVII-C-E-4M-176 CPU board, derived as per the segment connection */
static const uint8_t fontMap16[][CY_SEGLCD_16SEG_FONTMAP_SIZE] =
{
    /*  space           !             "             #             $             %             &             '     */
    {0x00U,0x00U},{0x06U,0x80U},{0x20U,0x01U},{0x00U,0x00U},{0x6DU,0x15U},{0xFFU,0xFFU},{0xFFU,0xFFU},{0x00U,0x40U},
    /*    (             )             *             +             ,             -             .             /     */
    {0x00U,0x0AU},{0x80U,0x20U},{0x80U,0x3BU},{0x40U,0x15U},{0xFFU,0xFFU},{0x40U,0x04U},{0x00U,0x80U},{0x00U,0x22U},
    /*    0             1             2             3             4             5             6             7     */
    {0x3FU,0x00U},{0x06U,0x00U},{0x5BU,0x04U},{0x4FU,0x04U},{0x66U,0x04U},{0x6DU,0x04U},{0x7DU,0x04U},{0x07U,0x00U},
    /*    8             9             :             ;             <             =             >             ?     */
    {0x7FU,0x04U},{0x6FU,0x04U},{0xFFU,0xFFU},{0xFFU,0xFFU},{0x00U,0x0AU},{0xFFU,0xFFU},{0x80U,0x20U},{0x03U,0x94U},
    /*    @             A             B             C             D             E             F             G     */
    {0xFFU,0xFFU},{0x77U,0x04U},{0x0FU,0x15U},{0x39U,0x00U},{0x0FU,0x11U},{0x79U,0x00U},{0x71U,0x00U},{0x3DU,0x04U},
    /*    H             I             J             K             L             M             N             O     */
    {0x76U,0x04U},{0x09U,0x11U},{0x1FU,0x00U},{0x70U,0x0AU},{0x38U,0x00U},{0xB6U,0x02U},{0xB6U,0x08U},{0x3FU,0x00U},
    /*    P             Q             R             S             T             U             V             W     */
    {0x73U,0x04U},{0x3FU,0x08U},{0x73U,0x0CU},{0x6DU,0x04U},{0x01U,0x11U},{0x3EU,0x00U},{0x30U,0x22U},{0x36U,0x28U},
    /*    X             Y             Z             [             \             ]             ^             _     */
    {0x80U,0x2AU},{0x80U,0x12U},{0x09U,0x22U},{0xFFU,0xFFU},{0x80U,0x08U},{0xFFU,0xFFU},{0xFFU,0xFFU},{0x08U,0x00U},
    /*    `             a             b             c             d             e             f             g     */
    {0x00U,0x40U},{0xFFU,0xFFU},{0xFFU,0xFFU},{0xFFU,0xFFU},{0xFFU,0xFFU},{0xFFU,0xFFU},{0xFFU,0xFFU},{0xFFU,0xFFU},
    /*    h             i             j             k             l             m             n             o     */
    {0xFFU,0xFFU},{0xFFU,0xFFU},{0xFFU,0xFFU},{0xFFU,0xFFU},{0xFFU,0xFFU},{0xFFU,0xFFU},{0xFFU,0xFFU},{0xFFU,0xFFU},
    /*    p             q             r             s             t             u             v             w     */
    {0xFFU,0xFFU},{0xFFU,0xFFU},{0xFFU,0xFFU},{0xFFU,0xFFU},{0xFFU,0xFFU},{0xFFU,0xFFU},{0xFFU,0xFFU},{0xFFU,0xFFU},
    /*    x             y             z             {             |             }             ~    */
    {0xFFU,0xFFU},{0xFFU,0xFFU},{0xFFU,0xFFU},{0xFFU,0xFFU},{0x00U,0x11U},{0xFFU,0xFFU},{0xFFU,0xFFU}
};

/* Displays font map structure */
SegLCD_CONST_MODIFIER cy_stc_seglcd_font_t cy_segLCD_16SegFont =
{
    .first   = ' ',
    .last    = '~',
    .ascii   = true,
    .fontMap = (uint8_t*)fontMap16
};

/* Displays properties structure definitions */
SegLCD_CONST_MODIFIER cy_stc_seglcd_disp_t SegLCD_Display0 =
{
    .type   = SegLCD_Display0_TYPE,
    .symNum = SegLCD_Display0_SYM_NUM,
    .invert = false,
    .pixMap = (uint32_t*)SegLCD_Display0_pixMap,
    .font   = &cy_segLCD_16SegFont
};


#endif /* H_CYCFG_SEGLCD */

/* [] END OF FILE */

