/**********************************************************************************
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such 
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or 
 * organization obtaining a copy of the software and accompanying 
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the 
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 *
 *********************************************************************************
 *
 *  $Date: 2023-01-24 19:09:01 +0530 (Tue, 24 Jan 2023) $
 *  $Revision: 320864 $
 *
 *********************************************************************************/
#ifndef LPDDR4_CFG_H
#define LPDDR4_CFG_H

/* XML Version 1.1.0 */
#define LPDDR4_XML_VERSION (10100)

#define CY_LPDDR4_FSP0_FREQ (0x3339D6D) /*decimal 53714285*/

#define CY_LPDDR4_FSP1_FREQ (0x2CD29C00) /*decimal 752000000*/

#define CY_LPDDR4_TREFI_NCK_COMPENSATE (0x15) /*decimal 21*/

#define DERATING_ALWAYS_ON (0x0) /*decimal 0*/

#define DERATING_DYNAMIC (0x1) /*decimal 1*/

#define DERATING_STRATEGY (0x0) /*decimal 0*/

#define DRIVER_MAJOR_VERSION (0x1) /*decimal 1*/

#define JESD209_4B_NCLK_TRAS (0x3) /*decimal 3*/

#define JESD209_4B_NCLK_TRAS_DERATED (0x2B) /*decimal 43*/

#define JESD209_4B_NCLK_TRCD (0x4) /*decimal 4*/

#define JESD209_4B_NCLK_TRP (0x4) /*decimal 4*/

#define JESD209_4B_NCLK_TRRD (0x4) /*decimal 4*/

#define JESD209_4B_NS_TRAS (0x2A) /*decimal 42*/

#define JESD209_4B_NS_TRAS_DERATED (1.88)

#define JESD209_4B_NS_TRCD (0x12) /*decimal 18*/

#define JESD209_4B_NS_TRCD_DERATED (19.88)

#define JESD209_4B_NS_TREFI (0xF40) /*decimal 3904*/

#define JESD209_4B_NS_TRP (0x12) /*decimal 18*/

#define JESD209_4B_NS_TRP_DERATED (19.88)

#define JESD209_4B_NS_TRRD (0xA) /*decimal 10*/

#define JESD209_4B_NS_TRRD_DERATED (11.88)

#define LPDDR4_ADDR0 (0xC520C41) /*decimal 206703681*/

#define LPDDR4_ADDR1 (0x73507) /*decimal 472327*/

#define LPDDR4_ADDR2 (0x2939460F) /*decimal 691619343*/

#define LPDDR4_ADDR3 (0x359C5ED5) /*decimal 899440341*/

#define LPDDR4_ADDR4 (0x779B) /*decimal 30619*/

#define LPDDR4_ADDR5 (0x4B16A) /*decimal 307562*/

#define LPDDR4_BISTCFG_CH0 (0x0) /*decimal 0*/

#define LPDDR4_BISTCFG_CH1 (0x0) /*decimal 0*/

#define LPDDR4_CIOR_CH0 (0x4) /*decimal 4*/

#define LPDDR4_CIOR_CH1 (0x4) /*decimal 4*/

#define LPDDR4_DIOR_SL0 (0x124) /*decimal 292*/

#define LPDDR4_DIOR_SL1 (0x124) /*decimal 292*/

#define LPDDR4_DIOR_SL2 (0x124) /*decimal 292*/

#define LPDDR4_DIOR_SL3 (0x124) /*decimal 292*/

#define LPDDR4_DLLCTLCA_CH0 (0x65) /*decimal 101*/

#define LPDDR4_DLLCTLCA_CH1 (0x65) /*decimal 101*/

#define LPDDR4_DLLCTLDQ_SL0 (0x65) /*decimal 101*/

#define LPDDR4_DLLCTLDQ_SL1 (0x65) /*decimal 101*/

#define LPDDR4_DLLCTLDQ_SL2 (0x65) /*decimal 101*/

#define LPDDR4_DLLCTLDQ_SL3 (0x65) /*decimal 101*/

#define LPDDR4_DMCFG (0xF2) /*decimal 242*/

#define LPDDR4_DMCTL (0x62A11F77) /*decimal 1654726519*/

#define LPDDR4_DQSDQCR (0x1FFAF00) /*decimal 33533696*/

#define LPDDR4_FREQUENCY_FSP0 (0x3339D6D) /*decimal 53714285*/

#define LPDDR4_FREQUENCY_FSP0_GUI (53.71)

#define LPDDR4_FREQUENCY_FSP1 (0x2CD29C00) /*decimal 752000000*/

#define LPDDR4_FREQUENCY_FSP1_GUI (0x2F0) /*decimal 752*/

#define LPDDR4_FSP0_CLOCK_PERIOD (18.62)

#define LPDDR4_FSP0_DATARATE (0.43)

#define LPDDR4_FSP1_CLOCK_PERIOD (1.33)

#define LPDDR4_FSP1_DATARATE (6.02)

#define LPDDR4_INECC0 (0x20000) /*decimal 131072*/

#define LPDDR4_INECC1 (0x0) /*decimal 0*/

#define LPDDR4_INECC2 (0x20000) /*decimal 131072*/

#define LPDDR4_LPMR1 (0x2404) /*decimal 9220*/

#define LPDDR4_LPMR11 (0xB40) /*decimal 2880*/

#define LPDDR4_LPMR12 (0x26CD) /*decimal 9933*/

#define LPDDR4_LPMR13 (0x0) /*decimal 0*/

#define LPDDR4_LPMR14 (0x6CD) /*decimal 1741*/

#define LPDDR4_LPMR2 (0x1200) /*decimal 4608*/

#define LPDDR4_LPMR22 (0x1D1D) /*decimal 7453*/

#define LPDDR4_LPMR3 (0x7931) /*decimal 31025*/

#define LPDDR4_PCCR_CH0 (0x100001F) /*decimal 16777247*/

#define LPDDR4_PCCR_CH1 (0x100001F) /*decimal 16777247*/

#define LPDDR4_PHY (0x0) /*decimal 0*/

#define LPDDR4_PLL_INPUT_FREQ (16.0)

#define LPDDR4_PLL_WAIT_TIME (0x2) /*decimal 2*/

#define LPDDR4_PTAR (0x0) /*decimal 0*/

#define LPDDR4_PTSR0 (0x1B) /*decimal 27*/

#define LPDDR4_PTSR1 (0x0) /*decimal 0*/

#define LPDDR4_PTSR10 (0x51515151) /*decimal 1364283729*/

#define LPDDR4_PTSR11 (0x51515151) /*decimal 1364283729*/

#define LPDDR4_PTSR12 (0x51515151) /*decimal 1364283729*/

#define LPDDR4_PTSR13 (0x51515151) /*decimal 1364283729*/

#define LPDDR4_PTSR14 (0x21212121) /*decimal 555819297*/

#define LPDDR4_PTSR15 (0x21212121) /*decimal 555819297*/

#define LPDDR4_PTSR16 (0x21212121) /*decimal 555819297*/

#define LPDDR4_PTSR17 (0x21212121) /*decimal 555819297*/

#define LPDDR4_PTSR18 (0x21212121) /*decimal 555819297*/

#define LPDDR4_PTSR19 (0x21212121) /*decimal 555819297*/

#define LPDDR4_PTSR2 (0x0) /*decimal 0*/

#define LPDDR4_PTSR20 (0x21212121) /*decimal 555819297*/

#define LPDDR4_PTSR21 (0x21212121) /*decimal 555819297*/

#define LPDDR4_PTSR22 (0x21212121) /*decimal 555819297*/

#define LPDDR4_PTSR23 (0x1820820) /*decimal 25298976*/

#define LPDDR4_PTSR24 (0xD5D50820) /*decimal 3587508256*/

#define LPDDR4_PTSR25 (0x820820) /*decimal 8521760*/

#define LPDDR4_PTSR3 (0x1B555555) /*decimal 458577237*/

#define LPDDR4_PTSR4 (0x81818181) /*decimal 2172748161*/

#define LPDDR4_PTSR5 (0x51515151) /*decimal 1364283729*/

#define LPDDR4_PTSR6 (0x51515151) /*decimal 1364283729*/

#define LPDDR4_PTSR7 (0x51515151) /*decimal 1364283729*/

#define LPDDR4_PTSR8 (0x51515151) /*decimal 1364283729*/

#define LPDDR4_PTSR9 (0x51515151) /*decimal 1364283729*/

#define LPDDR4_QOS_CPUSS (0x0) /*decimal 0*/

#define LPDDR4_QOS_VIDEOSS_RD (0xFFFC) /*decimal 65532*/

#define LPDDR4_QOS_VIDEOSS_WR (0x4000000) /*decimal 67108864*/

#define LPDDR4_RTCFG0_RT0 (0x3B1BDFD) /*decimal 61980157*/

#define LPDDR4_RTCFG0_RT1 (0x3B1BDFD) /*decimal 61980157*/

#define LPDDR4_RTCFG0_RT2 (0x3B1BDFD) /*decimal 61980157*/

#define LPDDR4_RTCFG0_RT3 (0x1B5BDFD) /*decimal 28687869*/

#define LPDDR4_RTCFG1_RT0 (0x8084225) /*decimal 134758949*/

#define LPDDR4_RTCFG1_RT1 (0x8084225) /*decimal 134758949*/

#define LPDDR4_RTCFG1_RT2 (0x8084225) /*decimal 134758949*/

#define LPDDR4_RTCFG1_RT3 (0x8084225) /*decimal 134758949*/

#define LPDDR4_RTGC0 (0x18610) /*decimal 99856*/

#define LPDDR4_RTGC1 (0x10388) /*decimal 66440*/

#define LPDDR4_TMNG_NCLK_ZQ_ITV_CALC (0x16F3000) /*decimal 24064000*/

#define LPDDR4_TMNG_NS_TREFI (3904.0)

#define LPDDR4_TRAINING (0x0) /*decimal 0*/

#define LPDDR4_TREG0 (0xA466B04) /*decimal 172387076*/

#define LPDDR4_TREG1 (0xCC02C6CB) /*decimal 3422734027*/

#define LPDDR4_TREG10 (0x5AF8C884) /*decimal 1526253700*/

#define LPDDR4_TREG11 (0x76C7D00) /*decimal 124550400*/

#define LPDDR4_TREG12 (0x237474A9) /*decimal 594834601*/

#define LPDDR4_TREG13 (0x2F2288) /*decimal 3089032*/

#define LPDDR4_TREG14 (0xBC3D10) /*decimal 12336400*/

#define LPDDR4_TREG15 (0x9897) /*decimal 39063*/

#define LPDDR4_TREG2 (0xA191D28) /*decimal 169418024*/

#define LPDDR4_TREG3 (0x36F4220B) /*decimal 921969163*/

#define LPDDR4_TREG4 (0x5E06201D) /*decimal 1577459741*/

#define LPDDR4_TREG5 (0x1F0B2326) /*decimal 520823590*/

#define LPDDR4_TREG6 (0x32807FFF) /*decimal 847282175*/

#define LPDDR4_TREG7 (0x9644A9F7) /*decimal 2521082359*/

#define LPDDR4_TREG8 (0x32A1FFFF) /*decimal 849477631*/

#define LPDDR4_TREG9 (0x316F3000) /*decimal 829370368*/

#define LPDDR4_VTGC (0x251481) /*decimal 2430081*/

#define PLL800_CONFIG_LOCK_DELAY (0x0) /*decimal 0*/

#define PLL800_CONFIG_PLL_FDBK_DIV (0x5E) /*decimal 94*/

#define PLL800_CONFIG_PLL_OUT_DIV (0xE) /*decimal 14*/

#define PLL800_CONFIG_PLL_REF_DIV (0x2) /*decimal 2*/

#define TRAINING_ALL_AT_ONCE (0x0) /*decimal 0*/

#define TRAINING_STEPWISE (0x1) /*decimal 1*/

#define USERSETTING_BURSTLENGTH (0x10) /*decimal 16*/

#define USERSETTING_CHANNEL_DENSITY (0x4) /*decimal 4*/

#define USERSETTING_DELTA_DQS_CHA_RETRAIN (0xA) /*decimal 10*/

#define USERSETTING_DELTA_DQS_CHB_RETRAIN (0xA) /*decimal 10*/

#define USERSETTING_DQS_OSC_RUNTIME (0x3F) /*decimal 63*/

#define USERSETTING_DRAM_BANK_EN (0x3) /*decimal 3*/

#define USERSETTING_DRAM_CHAN_EN (0x3) /*decimal 3*/

#define USERSETTING_FIXED_REFRESH_RATE (0x0) /*decimal 0*/

#define USERSETTING_INLINE_ECC_EN (0x0) /*decimal 0*/

#define USERSETTING_INT_ECC_EN (0x0) /*decimal 0*/

#define USERSETTING_INT_GC_FSM_EN (0x1) /*decimal 1*/

#define USERSETTING_PSVPFREQ (0x0) /*decimal 0*/

#define USERSETTING_RADIO (0x2) /*decimal 2*/

#define USERSETTING_RD_DBI (0x1) /*decimal 1*/

#define USERSETTING_READ_POST_AMBLE (0x0) /*decimal 0*/

#define USERSETTING_REFRESH_STRATEGY (0x1) /*decimal 1*/

#define USERSETTING_REF_POST_PULL_EN (0x0) /*decimal 0*/

#define USERSETTING_USE_PSVP (0x0) /*decimal 0*/

#define USERSETTING_WLS (0x0) /*decimal 0*/

#define USERSETTING_WRITE_POST_AMBLE (0x0) /*decimal 0*/

#define USERSETTING_WR_DBI (0x1) /*decimal 1*/

#define USERSETTING_ZQ_AUTO_EN (0x1) /*decimal 1*/

#endif /* LPDDR4_CFG_H */
